// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../index.js";

export interface AdrsListResponse {
    adrs: IcePanel.Adr[];
    nextCursor?: string | undefined;
}

export interface AdrsCreateResponse {
    adr: IcePanel.Adr;
}

export interface AdrsGetResponse {
    adr: IcePanel.Adr;
}

export interface AdrsUpdateResponse {
    adr: IcePanel.Adr;
}
