// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface ImportCreateResponse {
    landscapeImport: IcePanel.LandscapeImport;
}

export interface ImportGetResponse {
    landscapeImport: IcePanel.LandscapeImport;
}
