// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as IcePanel from "../../../../../index.js";
import { ExportClient } from "../resources/export/client/Client.js";

export declare namespace ConnectionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ConnectionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConnectionsClient.Options>;
    protected _export: ExportClient | undefined;

    constructor(options: ConnectionsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get export(): ExportClient {
        return (this._export ??= new ExportClient(this._options));
    }

    /**
     * @param {IcePanel.ModelConnectionsListRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.model.connections.list({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId"
     *     })
     */
    public async list(
        request: IcePanel.ModelConnectionsListRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.Page<IcePanel.ModelConnectionExpanded, IcePanel.model.ConnectionsListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: IcePanel.ModelConnectionsListRequest,
            ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsListResponse>> => {
                const { landscapeId, versionId, filter, expand, cursor, limit } = request;
                const _queryParams: Record<string, unknown> = {
                    filter,
                    expand: Array.isArray(expand) ? expand.map((item) => item) : expand != null ? expand : undefined,
                    cursor,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.IcePanelEnvironment.ApiV1,
                        `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    withCredentials: true,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as IcePanel.model.ConnectionsListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new IcePanel.BadRequestError(
                                _response.error.body as IcePanel.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new IcePanel.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new IcePanel.ForbiddenError(
                                _response.error.body as IcePanel.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                        case 422:
                            throw new IcePanel.UnprocessableEntityError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new IcePanel.InternalServerError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.IcePanelError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/landscapes/{landscapeId}/versions/{versionId}/model/connections",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<IcePanel.ModelConnectionExpanded, IcePanel.model.ConnectionsListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.modelConnections ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * @param {IcePanel.ModelConnectionCreateRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.TooManyRequestsError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.connections.create({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         body: {
     *             name: "name",
     *             originId: "originId",
     *             targetId: "targetId"
     *         }
     *     })
     */
    public create(
        request: IcePanel.ModelConnectionCreateRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: IcePanel.ModelConnectionCreateRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsCreateResponse>> {
        const { landscapeId, versionId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsCreateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new IcePanel.TooManyRequestsError(
                        _response.error.body as IcePanel.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections",
        );
    }

    /**
     * @param {IcePanel.ModelConnectionFindRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.model.connections.get({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelConnectionId: "modelConnectionId"
     *     })
     */
    public get(
        request: IcePanel.ModelConnectionFindRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: IcePanel.ModelConnectionFindRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsGetResponse>> {
        const { landscapeId, versionId, modelConnectionId, expand } = request;
        const _queryParams: Record<string, unknown> = {
            expand: Array.isArray(expand) ? expand.map((item) => item) : expand != null ? expand : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections/${core.url.encodePathParam(modelConnectionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsGetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections/{modelConnectionId}",
        );
    }

    /**
     * @param {IcePanel.ModelConnectionUpsertRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.TooManyRequestsError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.connections.upsert({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelConnectionId: "modelConnectionId",
     *         body: {
     *             name: "name",
     *             originId: "originId",
     *             targetId: "targetId"
     *         }
     *     })
     */
    public upsert(
        request: IcePanel.ModelConnectionUpsertRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsUpsertResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upsert(request, requestOptions));
    }

    private async __upsert(
        request: IcePanel.ModelConnectionUpsertRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsUpsertResponse>> {
        const {
            landscapeId,
            versionId,
            modelConnectionId,
            originConnector,
            targetConnector,
            updateDiagrams,
            body: _body,
        } = request;
        const _queryParams: Record<string, unknown> = {
            originConnector: originConnector != null ? originConnector : undefined,
            targetConnector: targetConnector != null ? targetConnector : undefined,
            updateDiagrams,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections/${core.url.encodePathParam(modelConnectionId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsUpsertResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new IcePanel.TooManyRequestsError(
                        _response.error.body as IcePanel.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections/{modelConnectionId}",
        );
    }

    /**
     * @param {IcePanel.ModelConnectionDeleteRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.connections.delete({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelConnectionId: "modelConnectionId"
     *     })
     */
    public delete(
        request: IcePanel.ModelConnectionDeleteRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsDeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: IcePanel.ModelConnectionDeleteRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsDeleteResponse>> {
        const { landscapeId, versionId, modelConnectionId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections/${core.url.encodePathParam(modelConnectionId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsDeleteResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections/{modelConnectionId}",
        );
    }

    /**
     * @param {IcePanel.ModelConnectionUpdateRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.TooManyRequestsError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.connections.update({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelConnectionId: "modelConnectionId",
     *         body: {}
     *     })
     */
    public update(
        request: IcePanel.ModelConnectionUpdateRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: IcePanel.ModelConnectionUpdateRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsUpdateResponse>> {
        const { landscapeId, versionId, modelConnectionId, updateDiagrams, body: _body } = request;
        const _queryParams: Record<string, unknown> = {
            updateDiagrams,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections/${core.url.encodePathParam(modelConnectionId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsUpdateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new IcePanel.TooManyRequestsError(
                        _response.error.body as IcePanel.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections/{modelConnectionId}",
        );
    }

    /**
     * Generate a description for a model connection
     *
     * @param {IcePanel.ModelConnectionGenerateDescriptionRequest} request
     * @param {ConnectionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.connections.generateDescription({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelConnectionId: "modelConnectionId",
     *         type: "caption"
     *     })
     */
    public generateDescription(
        request: IcePanel.ModelConnectionGenerateDescriptionRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ConnectionsGenerateDescriptionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__generateDescription(request, requestOptions));
    }

    private async __generateDescription(
        request: IcePanel.ModelConnectionGenerateDescriptionRequest,
        requestOptions?: ConnectionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ConnectionsGenerateDescriptionResponse>> {
        const { landscapeId, versionId, modelConnectionId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/connections/${core.url.encodePathParam(modelConnectionId)}/generate-description`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as IcePanel.model.ConnectionsGenerateDescriptionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/landscapes/{landscapeId}/versions/{versionId}/model/connections/{modelConnectionId}/generate-description",
        );
    }
}
