// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../errors/index.js";
import * as IcePanel from "../../../../../index.js";
import { ExportClient } from "../resources/export/client/Client.js";

export declare namespace ObjectsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ObjectsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ObjectsClient.Options>;
    protected _export: ExportClient | undefined;

    constructor(options: ObjectsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get export(): ExportClient {
        return (this._export ??= new ExportClient(this._options));
    }

    /**
     * Returns the incoming and outgoing dependencies for each requested object. Objects can be specified by ID or by label key-value pairs (or both): label pairs use OR semantics so an object matching any pair is included. Results are filtered by tags and/or technologies when provided: within each filter array the semantics are OR (any match passes), and between the two filter dimensions the semantics are AND (an object must satisfy both when both are specified).
     *
     * @param {IcePanel.ModelObjectDependenciesListRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.model.objects.dependenciesList({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         filter: {}
     *     })
     */
    public dependenciesList(
        request: IcePanel.ModelObjectDependenciesListRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<Record<string, IcePanel.model.ObjectsDependenciesListResponseValue>> {
        return core.HttpResponsePromise.fromPromise(this.__dependenciesList(request, requestOptions));
    }

    private async __dependenciesList(
        request: IcePanel.ModelObjectDependenciesListRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, IcePanel.model.ObjectsDependenciesListResponseValue>>> {
        const { landscapeId, versionId, filter } = request;
        const _queryParams: Record<string, unknown> = {
            filter,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/dependencies`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Record<string, IcePanel.model.ObjectsDependenciesListResponseValue>,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/model/dependencies",
        );
    }

    /**
     * @param {IcePanel.ModelObjectsListRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.model.objects.list({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId"
     *     })
     */
    public async list(
        request: IcePanel.ModelObjectsListRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.Page<IcePanel.ModelObjectExpanded, IcePanel.model.ObjectsListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: IcePanel.ModelObjectsListRequest,
            ): Promise<core.WithRawResponse<IcePanel.model.ObjectsListResponse>> => {
                const { landscapeId, versionId, filter, expand, cursor, limit } = request;
                const _queryParams: Record<string, unknown> = {
                    filter,
                    expand: Array.isArray(expand) ? expand.map((item) => item) : expand != null ? expand : undefined,
                    cursor,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.IcePanelEnvironment.ApiV1,
                        `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    withCredentials: true,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as IcePanel.model.ObjectsListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new IcePanel.BadRequestError(
                                _response.error.body as IcePanel.Error_,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new IcePanel.UnauthorizedError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new IcePanel.ForbiddenError(
                                _response.error.body as IcePanel.Error_,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                        case 422:
                            throw new IcePanel.UnprocessableEntityError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new IcePanel.InternalServerError(
                                _response.error.body as unknown,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.IcePanelError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/landscapes/{landscapeId}/versions/{versionId}/model/objects",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<IcePanel.ModelObjectExpanded, IcePanel.model.ObjectsListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.nextCursor != null &&
                !(typeof response?.nextCursor === "string" && response?.nextCursor === ""),
            getItems: (response) => response?.modelObjects ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.nextCursor));
            },
        });
    }

    /**
     * @param {IcePanel.ModelObjectCreateRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.objects.create({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         body: {
     *             name: "name",
     *             type: "actor"
     *         }
     *     })
     */
    public create(
        request: IcePanel.ModelObjectCreateRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ObjectsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: IcePanel.ModelObjectCreateRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ObjectsCreateResponse>> {
        const { landscapeId, versionId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.model.ObjectsCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/landscapes/{landscapeId}/versions/{versionId}/model/objects",
        );
    }

    /**
     * @param {IcePanel.ModelObjectFindRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     *
     * @example
     *     await client.model.objects.get({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelObjectId: "modelObjectId"
     *     })
     */
    public get(
        request: IcePanel.ModelObjectFindRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ObjectsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: IcePanel.ModelObjectFindRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ObjectsGetResponse>> {
        const { landscapeId, versionId, modelObjectId, expand } = request;
        const _queryParams: Record<string, unknown> = {
            expand: Array.isArray(expand) ? expand.map((item) => item) : expand != null ? expand : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects/${core.url.encodePathParam(modelObjectId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.model.ObjectsGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}",
        );
    }

    /**
     * @param {IcePanel.ModelObjectUpsertRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.objects.upsert({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelObjectId: "modelObjectId",
     *         body: {
     *             name: "name",
     *             type: "actor"
     *         }
     *     })
     */
    public upsert(
        request: IcePanel.ModelObjectUpsertRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ObjectsUpsertResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upsert(request, requestOptions));
    }

    private async __upsert(
        request: IcePanel.ModelObjectUpsertRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ObjectsUpsertResponse>> {
        const { landscapeId, versionId, modelObjectId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects/${core.url.encodePathParam(modelObjectId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.model.ObjectsUpsertResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}",
        );
    }

    /**
     * @param {IcePanel.ModelObjectDeleteRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.objects.delete({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelObjectId: "modelObjectId"
     *     })
     */
    public delete(
        request: IcePanel.ModelObjectDeleteRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ObjectsDeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: IcePanel.ModelObjectDeleteRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ObjectsDeleteResponse>> {
        const { landscapeId, versionId, modelObjectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects/${core.url.encodePathParam(modelObjectId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.model.ObjectsDeleteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}",
        );
    }

    /**
     * @param {IcePanel.ModelObjectUpdateRequest} request
     * @param {ObjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link IcePanel.BadRequestError}
     * @throws {@link IcePanel.UnauthorizedError}
     * @throws {@link IcePanel.ForbiddenError}
     * @throws {@link IcePanel.NotFoundError}
     * @throws {@link IcePanel.ConflictError}
     * @throws {@link IcePanel.UnprocessableEntityError}
     * @throws {@link IcePanel.InternalServerError}
     * @throws {@link IcePanel.ServiceUnavailableError}
     *
     * @example
     *     await client.model.objects.update({
     *         landscapeId: "landscapeId",
     *         versionId: "versionId",
     *         modelObjectId: "modelObjectId",
     *         body: {}
     *     })
     */
    public update(
        request: IcePanel.ModelObjectUpdateRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): core.HttpResponsePromise<IcePanel.model.ObjectsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: IcePanel.ModelObjectUpdateRequest,
        requestOptions?: ObjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<IcePanel.model.ObjectsUpdateResponse>> {
        const { landscapeId, versionId, modelObjectId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.IcePanelEnvironment.ApiV1,
                `landscapes/${core.url.encodePathParam(landscapeId)}/versions/${core.url.encodePathParam(versionId)}/model/objects/${core.url.encodePathParam(modelObjectId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            withCredentials: true,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as IcePanel.model.ObjectsUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new IcePanel.BadRequestError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 401:
                    throw new IcePanel.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new IcePanel.ForbiddenError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 404:
                    throw new IcePanel.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new IcePanel.ConflictError(_response.error.body as IcePanel.Error_, _response.rawResponse);
                case 422:
                    throw new IcePanel.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new IcePanel.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new IcePanel.ServiceUnavailableError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.IcePanelError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/landscapes/{landscapeId}/versions/{versionId}/model/objects/{modelObjectId}",
        );
    }
}
