// This file was auto-generated by Fern from our API Definition.

import type * as IcePanel from "../../../../../index.js";

export interface LogsListResponse {
    actionLogs: IcePanel.ActionLog[];
    nextCursor?: string | undefined;
}

export interface LogsGetResponse {
    actionLog: IcePanel.ActionLog;
}

export interface LogsListChildrenResponse {
    actionLogs: IcePanel.ActionLog[];
    nextCursor?: string | undefined;
}
