// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../../src/api/index";
import { IcePanelClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TechnologiesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            catalogTechnologies: [
                {
                    category: "category",
                    color: "blue",
                    deprecatedAt: "2024-01-15T09:30:00Z",
                    description: "description",
                    docsUrl: "docsUrl",
                    iconUrlDark: "iconUrlDark",
                    iconUrlLight: "iconUrlLight",
                    name: "name",
                    nameShort: "nameShort",
                    provider: "aws",
                    rejectionMessage: "rejectionMessage",
                    rejectionReason: "duplicate",
                    restrictions: ["actor"],
                    status: "approved",
                    type: "data-storage",
                    updatesUrl: "updatesUrl",
                    websiteUrl: "websiteUrl",
                    awsXmlSelector: "awsXmlSelector",
                    azureUpdatesKeyword: "azureUpdatesKeyword",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    defaultSlug: "defaultSlug",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    disabled: true,
                    iconUrl: "iconUrl",
                    id: "id",
                    organizationId: "organizationId",
                    slugs: ["slugs"],
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    updatesXmlUrl: "updatesXmlUrl",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.technologies.list({
            organizationId: "organizationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.list({
                organizationId: "organizationId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = {
            catalogTechnology: {
                category: "category",
                color: "blue",
                deprecatedAt: "2024-01-15T09:30:00Z",
                description: "description",
                docsUrl: "docsUrl",
                iconUrlDark: "iconUrlDark",
                iconUrlLight: "iconUrlLight",
                name: "name",
                nameShort: "nameShort",
                provider: "aws",
                rejectionMessage: "rejectionMessage",
                rejectionReason: "duplicate",
                restrictions: ["actor"],
                status: "approved",
                type: "data-storage",
                updatesUrl: "updatesUrl",
                websiteUrl: "websiteUrl",
                awsXmlSelector: "awsXmlSelector",
                azureUpdatesKeyword: "azureUpdatesKeyword",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                defaultSlug: "defaultSlug",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                disabled: true,
                iconUrl: "iconUrl",
                id: "id",
                organizationId: "organizationId",
                slugs: ["slugs"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                updatesXmlUrl: "updatesXmlUrl",
            },
        };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.technologies.create({
            organizationId: "organizationId",
            body: {
                color: "blue",
                name: "name",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { color: "blue", name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/organizations/organizationId/technologies")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.create({
                organizationId: "organizationId",
                body: {
                    color: "blue",
                    name: "name",
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            catalogTechnology: {
                category: "category",
                color: "blue",
                deprecatedAt: "2024-01-15T09:30:00Z",
                description: "description",
                docsUrl: "docsUrl",
                iconUrlDark: "iconUrlDark",
                iconUrlLight: "iconUrlLight",
                name: "name",
                nameShort: "nameShort",
                provider: "aws",
                rejectionMessage: "rejectionMessage",
                rejectionReason: "duplicate",
                restrictions: ["actor"],
                status: "approved",
                type: "data-storage",
                updatesUrl: "updatesUrl",
                websiteUrl: "websiteUrl",
                awsXmlSelector: "awsXmlSelector",
                azureUpdatesKeyword: "azureUpdatesKeyword",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                defaultSlug: "defaultSlug",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                disabled: true,
                iconUrl: "iconUrl",
                id: "id",
                organizationId: "organizationId",
                slugs: ["slugs"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                updatesXmlUrl: "updatesXmlUrl",
            },
        };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.technologies.get({
            organizationId: "organizationId",
            catalogTechnologyId: "catalogTechnologyId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.get({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.technologies.delete({
            organizationId: "organizationId",
            catalogTechnologyId: "catalogTechnologyId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/organizations/organizationId/technologies/catalogTechnologyId")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.delete({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            catalogTechnology: {
                category: "category",
                color: "blue",
                deprecatedAt: "2024-01-15T09:30:00Z",
                description: "description",
                docsUrl: "docsUrl",
                iconUrlDark: "iconUrlDark",
                iconUrlLight: "iconUrlLight",
                name: "name",
                nameShort: "nameShort",
                provider: "aws",
                rejectionMessage: "rejectionMessage",
                rejectionReason: "duplicate",
                restrictions: ["actor"],
                status: "approved",
                type: "data-storage",
                updatesUrl: "updatesUrl",
                websiteUrl: "websiteUrl",
                awsXmlSelector: "awsXmlSelector",
                azureUpdatesKeyword: "azureUpdatesKeyword",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                defaultSlug: "defaultSlug",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                disabled: true,
                iconUrl: "iconUrl",
                id: "id",
                organizationId: "organizationId",
                slugs: ["slugs"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                updatesXmlUrl: "updatesXmlUrl",
            },
        };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.technologies.update({
            organizationId: "organizationId",
            catalogTechnologyId: "catalogTechnologyId",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/organizations/organizationId/technologies/catalogTechnologyId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.technologies.update({
                organizationId: "organizationId",
                catalogTechnologyId: "catalogTechnologyId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });
});
