// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../src/api/index";
import { IcePanelClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CommentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            comments: [
                {
                    body: { content: "content", status: "open", type: "question" },
                    commit: 1.1,
                    mentionedUserIds: ["mentionedUserIds"],
                    handleId: "handleId",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    diagrams: { key: { commentId: "commentId", id: "id" } },
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    replyCount: 1.1,
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.list({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = {
            comment: {
                body: { content: "content", showContentPreview: true, status: "open", type: "question" },
                commit: 1.1,
                mentionedUserIds: ["mentionedUserIds"],
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: { key: { commentId: "commentId", id: "id" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                replyCount: 1.1,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                body: {
                    content: "content",
                    status: "open",
                    type: "question",
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            comment: {
                body: { content: "content", showContentPreview: true, status: "open", type: "question" },
                commit: 1.1,
                mentionedUserIds: ["mentionedUserIds"],
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: { key: { commentId: "commentId", id: "id" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                replyCount: 1.1,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
            commentId: "commentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = {
            comment: {
                body: { content: "content", showContentPreview: true, status: "open", type: "question" },
                commit: 1.1,
                mentionedUserIds: ["mentionedUserIds"],
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: { key: { commentId: "commentId", id: "id" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                replyCount: 1.1,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.upsert({
            landscapeId: "landscapeId",
            versionId: "versionId",
            commentId: "commentId",
            body: {
                body: {
                    content: "content",
                    status: "open",
                    type: "question",
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("upsert (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("upsert (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { body: { content: "content", status: "open", type: "question" } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {
                    body: {
                        content: "content",
                        status: "open",
                        type: "question",
                    },
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { commit: 1.1 };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
            commentId: "commentId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            comment: {
                body: { content: "content", showContentPreview: true, status: "open", type: "question" },
                commit: 1.1,
                mentionedUserIds: ["mentionedUserIds"],
                handleId: "handleId",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                diagrams: { key: { commentId: "commentId", id: "id" } },
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                replyCount: 1.1,
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
            },
        };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            commentId: "commentId",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/comments/commentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.comments.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                commentId: "commentId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });
});
