// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../src/api/index";
import { IcePanelClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("DraftsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            drafts: [
                {
                    changeSummary: {
                        createdAt: "2024-01-15T09:30:00Z",
                        summary: "summary",
                        updatedAt: "2024-01-15T09:30:00Z",
                    },
                    commit: 1.1,
                    handleId: "handleId",
                    labels: { key: "value" },
                    name: "name",
                    status: "in-progress",
                    summaryDirtiedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    deletedAt: "2024-01-15T09:30:00Z",
                    deletedBy: "user",
                    deletedById: "deletedById",
                    headVersionId: "headVersionId",
                    id: "id",
                    landscapeId: "landscapeId",
                    latestEntityId: "latestEntityId",
                    mergedAt: "2024-01-15T09:30:00Z",
                    mergedBy: "user",
                    mergedById: "mergedById",
                    originVersionId: "originVersionId",
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                    version: 1.1,
                    versionId: "versionId",
                    viewedAt: "2024-01-15T09:30:00Z",
                    viewedBy: "user",
                    viewedById: "viewedById",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.list({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.list({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = {
            draft: {
                changeSummary: {
                    createdAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                commit: 1.1,
                handleId: "handleId",
                labels: { key: "value" },
                name: "name",
                status: "in-progress",
                summaryDirtiedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                headVersionId: "headVersionId",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                mergedAt: "2024-01-15T09:30:00Z",
                mergedBy: "user",
                mergedById: "mergedById",
                originVersionId: "originVersionId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.create({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {
                name: "name",
                status: "in-progress",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.create({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            draft: {
                changeSummary: {
                    createdAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                commit: 1.1,
                handleId: "handleId",
                labels: { key: "value" },
                name: "name",
                status: "in-progress",
                summaryDirtiedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                headVersionId: "headVersionId",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                mergedAt: "2024-01-15T09:30:00Z",
                mergedBy: "user",
                mergedById: "mergedById",
                originVersionId: "originVersionId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
            draftId: "draftId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = {
            draft: {
                changeSummary: {
                    createdAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                commit: 1.1,
                handleId: "handleId",
                labels: { key: "value" },
                name: "name",
                status: "in-progress",
                summaryDirtiedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                headVersionId: "headVersionId",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                mergedAt: "2024-01-15T09:30:00Z",
                mergedBy: "user",
                mergedById: "mergedById",
                originVersionId: "originVersionId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.upsert({
            landscapeId: "landscapeId",
            versionId: "versionId",
            draftId: "draftId",
            body: {
                name: "name",
                status: "in-progress",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("upsert (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("upsert (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("upsert (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", status: "in-progress" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.upsert({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {
                    name: "name",
                    status: "in-progress",
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
            draftId: "draftId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            draft: {
                changeSummary: {
                    createdAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                commit: 1.1,
                handleId: "handleId",
                labels: { key: "value" },
                name: "name",
                status: "in-progress",
                summaryDirtiedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                headVersionId: "headVersionId",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                mergedAt: "2024-01-15T09:30:00Z",
                mergedBy: "user",
                mergedById: "mergedById",
                originVersionId: "originVersionId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            draftId: "draftId",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.TooManyRequestsError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId/drafts/draftId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("merge (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            draft: {
                changeSummary: {
                    createdAt: "2024-01-15T09:30:00Z",
                    summary: "summary",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
                commit: 1.1,
                handleId: "handleId",
                labels: { key: "value" },
                name: "name",
                status: "in-progress",
                summaryDirtiedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                deletedAt: "2024-01-15T09:30:00Z",
                deletedBy: "user",
                deletedById: "deletedById",
                headVersionId: "headVersionId",
                id: "id",
                landscapeId: "landscapeId",
                latestEntityId: "latestEntityId",
                mergedAt: "2024-01-15T09:30:00Z",
                mergedBy: "user",
                mergedById: "mergedById",
                originVersionId: "originVersionId",
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
                version: 1.1,
                versionId: "versionId",
                viewedAt: "2024-01-15T09:30:00Z",
                viewedBy: "user",
                viewedById: "viewedById",
            },
        };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.drafts.merge({
            landscapeId: "landscapeId",
            versionId: "versionId",
            draftId: "draftId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("merge (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("merge (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("merge (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("merge (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("merge (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("merge (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("merge (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("merge (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions/versionId/drafts/draftId/merge")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.drafts.merge({
                landscapeId: "landscapeId",
                versionId: "versionId",
                draftId: "draftId",
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });
});
