// This file was auto-generated by Fern from our API Definition.

import * as IcePanel from "../../src/api/index";
import { IcePanelClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("VersionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            nextCursor: "nextCursor",
            versions: [
                {
                    modelHandleId: "modelHandleId",
                    name: "name",
                    notes: "notes",
                    completedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    createdBy: "user",
                    createdById: "createdById",
                    id: "id",
                    landscapeId: "landscapeId",
                    tags: ["tags"],
                    updatedAt: "2024-01-15T09:30:00Z",
                    updatedBy: "user",
                    updatedById: "updatedById",
                },
            ],
        };

        server
            .mockEndpoint({ once: false })
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.versions.list({
            landscapeId: "landscapeId",
        });

        expect(expected.versions).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.versions).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.list({
                landscapeId: "landscapeId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", notes: "notes" };
        const rawResponseBody = {
            version: {
                modelHandleId: "modelHandleId",
                name: "name",
                notes: "notes",
                completedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                tags: ["tags"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
            },
        };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.versions.create({
            landscapeId: "landscapeId",
            body: {
                name: "name",
                notes: "notes",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", notes: "strawberry" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/landscapes/landscapeId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.create({
                landscapeId: "landscapeId",
                body: {
                    name: "x",
                    notes: "strawberry",
                },
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            version: {
                modelHandleId: "modelHandleId",
                name: "name",
                notes: "notes",
                completedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                tags: ["tags"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
            },
        };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.versions.get({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.get({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.versions.delete({
            landscapeId: "landscapeId",
            versionId: "versionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("delete (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("delete (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/landscapes/landscapeId/versions/versionId")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.delete({
                landscapeId: "landscapeId",
                versionId: "versionId",
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            version: {
                modelHandleId: "modelHandleId",
                name: "name",
                notes: "notes",
                completedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                createdBy: "user",
                createdById: "createdById",
                id: "id",
                landscapeId: "landscapeId",
                tags: ["tags"],
                updatedAt: "2024-01-15T09:30:00Z",
                updatedBy: "user",
                updatedById: "updatedById",
            },
        };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.versions.update({
            landscapeId: "landscapeId",
            versionId: "versionId",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { message: "message" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.UnprocessableEntityError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.InternalServerError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new IcePanelClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            bearerAuth: { token: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/landscapes/landscapeId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.versions.update({
                landscapeId: "landscapeId",
                versionId: "versionId",
                body: {},
            });
        }).rejects.toThrow(IcePanel.ServiceUnavailableError);
    });
});
